package dev.birb.wgpu.rust

import java.lang.foreign.Arena
import java.lang.foreign.FunctionDescriptor
import java.lang.foreign.Linker
import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.SymbolLookup
import java.lang.foreign.ValueLayout
import java.lang.invoke.MethodHandle

/**
 * Foreign-function bindings to the C ABI exported by `rust/wgpu-mc-jni`
 * (see `rust/wgpu-mc-jni/bindings.h`, generated by cbindgen).
 *
 * The upstream Fabric module generates these with the `jextract` Gradle plugin. The NeoForge
 * module binds the same header by hand instead: the header is small and stable, and doing it here
 * keeps the whole ABI in one reviewable file with no extra toolchain to download. The downcall
 * surface is identical.
 *
 * Layouts and field offsets mirror `bindings.h` 1:1. Every field of every struct in that header
 * is either a pointer or a 64-bit value, so the C compiler inserts no padding and the offsets are
 * exactly the ones written out below.
 */
object WmNative {

    private const val LIBRARY_NAME = "wgpu_mc_jni"

    private val linker: Linker = Linker.nativeLinker()

    private val libraryPath: String by lazy { WgpuNative.resolveNativeLibrary(LIBRARY_NAME) }

    private val lookup: SymbolLookup by lazy { SymbolLookup.libraryLookup(libraryPath, Arena.global()) }

    private fun handle(name: String, descriptor: FunctionDescriptor): MethodHandle {
        val symbol = lookup.find(name).orElseThrow {
            IllegalStateException("Native symbol '$name' is missing from $LIBRARY_NAME; rebuild rust/wgpu-mc-jni")
        }
        return linker.downcallHandle(symbol, descriptor)
    }

    // Layouts for the scalar kinds used by the ABI, re-exported so backend code can write struct
    // fields without importing ValueLayout itself.
    @JvmField val PTR: java.lang.foreign.AddressLayout = ValueLayout.ADDRESS

    /** Alias for [PTR], matching the name used at the struct-write call sites. */
    @JvmField val ADDRESS: java.lang.foreign.AddressLayout = ValueLayout.ADDRESS
    @JvmField val LONG: ValueLayout.OfLong = ValueLayout.JAVA_LONG
    @JvmField val INT: ValueLayout.OfInt = ValueLayout.JAVA_INT
    @JvmField val FLOAT: ValueLayout.OfFloat = ValueLayout.JAVA_FLOAT
    @JvmField val DOUBLE: ValueLayout.OfDouble = ValueLayout.JAVA_DOUBLE

    // ------------------------------------------------------------------
    // Struct layouts (mirror bindings.h)
    // ------------------------------------------------------------------

    /** `struct BlazeAttachmentDescriptor__________f32__________4 { const uint8_t *texture_view; const float (*clear_value)[4]; }` */
    @JvmField val ATTACHMENT_F32X4: MemoryLayout = MemoryLayout.structLayout(PTR, PTR)

    /** `struct BlazeAttachmentDescriptor_f64 { const uint8_t *texture_view; const double *clear_value; }` */
    @JvmField val ATTACHMENT_F64: MemoryLayout = MemoryLayout.structLayout(PTR, PTR)

    /** `struct RawArray_X { const struct X *contents; uint64_t size; }` - one layout serves them all. */
    @JvmField val RAW_ARRAY: MemoryLayout = MemoryLayout.structLayout(PTR, LONG)

    /** `struct BlazeRenderPassDescriptor { const RawArray_...f32x4 *attachments; const BlazeAttachmentDescriptor_f64 *depth_attachment; }` */
    @JvmField val RENDER_PASS_DESCRIPTOR: MemoryLayout = MemoryLayout.structLayout(PTR, PTR)

    /** `struct BindGroupEntryDescriptor { UniformType type_; char *name; GpuFormat texture_format; }` */
    @JvmField val BIND_GROUP_ENTRY: MemoryLayout = MemoryLayout.structLayout(LONG, PTR, LONG)

    /** `struct BlazeBindGroupLayout { RawArray_BindGroupEntryDescriptor *entries; }` */
    @JvmField val BIND_GROUP_LAYOUT: MemoryLayout = MemoryLayout.structLayout(PTR)

    /**
     * `struct BlazeColorTargetState { BlazeBlendState *blend; GpuFormat format; uint32_t write_mask; }`
     *
     * The pointer is null when the pipeline asks for no blending at all. The four bytes of padding
     * after `write_mask` are what puts the struct at 24 bytes, matching Rust's `#[repr(C)]` layout.
     */
    @JvmField val COLOR_TARGET_STATE: MemoryLayout =
        MemoryLayout.structLayout(PTR, LONG, INT, MemoryLayout.paddingLayout(4))

    /** `struct BlazeBlendState { BlendFactor src_color; BlendFactor dst_color; BlendFactor src_alpha; BlendFactor dst_alpha; }` */
    @JvmField val BLEND_STATE: MemoryLayout = MemoryLayout.structLayout(LONG, LONG, LONG, LONG)

    /** Offsets inside [COLOR_TARGET_STATE]. */
    const val COLOR_TARGET_BLEND = 0L
    const val COLOR_TARGET_FORMAT = 8L
    const val COLOR_TARGET_WRITE_MASK = 16L

    /** Offsets inside [BLEND_STATE]. */
    const val BLEND_STATE_SRC_COLOR = 0L
    const val BLEND_STATE_DST_COLOR = 8L
    const val BLEND_STATE_SRC_ALPHA = 16L
    const val BLEND_STATE_DST_ALPHA = 24L

    /**
     * `struct BlazeDepthStencilState { uint64_t compare_function; uint64_t active; int32_t bias_constant; float bias_slope_scale; }`
     *
     * `compare_function` is a `CompareFunction` value from this ABI's own numbering, and `active`
     * doubles as `writeDepth`.
     */
    @JvmField val DEPTH_STENCIL_STATE: MemoryLayout = MemoryLayout.structLayout(LONG, LONG, INT, FLOAT)

    // CompareFunction enum (uint64_t)

    const val COMPARE_NEVER = 0L
    const val COMPARE_LESS = 1L
    const val COMPARE_EQUAL = 2L
    const val COMPARE_LESS_EQUAL = 3L
    const val COMPARE_GREATER = 4L
    const val COMPARE_NOT_EQUAL = 5L
    const val COMPARE_GREATER_EQUAL = 6L
    const val COMPARE_ALWAYS = 7L

    // BlendFactor enum (uint64_t). The numbering is this ABI's own; `WgpuFormat` maps Minecraft's
    // `SourceFactor`/`DestFactor` onto it by name.

    const val BLEND_ZERO = 0L
    const val BLEND_ONE = 1L
    const val BLEND_SRC_COLOR = 2L
    const val BLEND_ONE_MINUS_SRC_COLOR = 3L
    const val BLEND_DST_COLOR = 4L
    const val BLEND_ONE_MINUS_DST_COLOR = 5L
    const val BLEND_SRC_ALPHA = 6L
    const val BLEND_ONE_MINUS_SRC_ALPHA = 7L
    const val BLEND_DST_ALPHA = 8L
    const val BLEND_ONE_MINUS_DST_ALPHA = 9L
    const val BLEND_SRC_ALPHA_SATURATE = 10L
    const val BLEND_CONSTANT = 11L
    const val BLEND_ONE_MINUS_CONSTANT = 12L

    // GpuFormat enum (uint64_t)


    /** `struct VertexFormatElement { uint64_t offset; GpuFormat format; char *name; }` */
    @JvmField val VERTEX_FORMAT_ELEMENT: MemoryLayout = MemoryLayout.structLayout(LONG, LONG, PTR)

    /** `struct VertexFormat { RawArray_VertexFormatElement *elements; uint64_t vertex_size; }` */
    @JvmField val VERTEX_FORMAT: MemoryLayout = MemoryLayout.structLayout(PTR, LONG)

    /** `struct RenderPipeline`, in declaration order. */
    @JvmField val RENDER_PIPELINE: MemoryLayout = MemoryLayout.structLayout(
        PTR,  // name
        PTR,  // bind_group_layouts
        PTR,  // color_target_states
        PTR,  // depth_stencil_state
        PTR,  // vertex_formats
        PTR,  // vertex_shader
        PTR,  // fragment_shader
        PTR,  // directives
        PTR,  // frag_state
        LONG, // primitive_topology
        LONG, // cull
    )

    // ------------------------------------------------------------------
    // The draw call
    //
    // One struct carries a whole draw: the pipeline, the buffers, the parameters and every binding,
    // so the JVM writes it and makes a single downcall. The binding array is indexed by the slot the
    // pipeline's plan gave each binding - see `pipeline_bindings` - and only the first
    // `bindings_len` entries are read, so a draw writes as many as it has bindings and no more.
    // ------------------------------------------------------------------

    /** `struct PlanBinding { char *name; char *declared_name; uint32_t set; uint32_t binding; uint32_t kind; uint32_t _pad; }` */
    @JvmField val PLAN_BINDING: MemoryLayout = MemoryLayout.structLayout(PTR, PTR, INT, INT, INT, INT)

    /** `struct DrawBinding { uint32_t kind; uint32_t _pad; const uint8_t *resource; uint64_t offset; uint64_t length; }` */
    @JvmField val DRAW_BINDING: MemoryLayout = MemoryLayout.structLayout(INT, INT, PTR, LONG, LONG)

    /** `struct DrawVertexBuffer { const uint8_t *buffer; uint64_t offset; uint64_t size; }` */
    @JvmField val DRAW_VERTEX_BUFFER: MemoryLayout = MemoryLayout.structLayout(PTR, LONG, LONG)

    /** `struct DrawCall`, in declaration order. */
    @JvmField val DRAW_CALL: MemoryLayout = MemoryLayout.structLayout(
        PTR,  // pipeline
        INT,  // vertex_buffer_mask
        INT,  // index_format
        INT,  // indexed
        INT,  // bindings_len
        INT,  // first
        INT,  // count
        INT,  // base_vertex
        INT,  // instance_count
        PTR,  // index_buffer
        MemoryLayout.sequenceLayout(MAX_VERTEX_BUFFERS.toLong(), DRAW_VERTEX_BUFFER),
        MemoryLayout.sequenceLayout(MAX_DRAW_BINDINGS.toLong(), DRAW_BINDING),
    )

    /** Offsets inside [DRAW_CALL]. */
    const val DRAW_CALL_PIPELINE = 0L
    const val DRAW_CALL_VERTEX_BUFFER_MASK = 8L
    const val DRAW_CALL_INDEX_FORMAT = 12L
    const val DRAW_CALL_INDEXED = 16L
    const val DRAW_CALL_BINDINGS_LEN = 20L
    const val DRAW_CALL_FIRST = 24L
    const val DRAW_CALL_COUNT = 28L
    const val DRAW_CALL_BASE_VERTEX = 32L
    const val DRAW_CALL_INSTANCE_COUNT = 36L
    const val DRAW_CALL_INDEX_BUFFER = 40L
    const val DRAW_CALL_VERTEX_BUFFERS = 48L
    const val DRAW_CALL_BINDINGS = 240L

    /** Offsets inside [PLAN_BINDING] and [DRAW_BINDING]. */
    const val PLAN_BINDING_NAME = 0L
    const val PLAN_BINDING_DECLARED_NAME = 8L
    const val PLAN_BINDING_SET = 16L
    const val PLAN_BINDING_BINDING = 20L
    const val PLAN_BINDING_KIND = 24L

    const val DRAW_BINDING_KIND = 0L
    const val DRAW_BINDING_RESOURCE = 8L
    const val DRAW_BINDING_OFFSET = 16L
    const val DRAW_BINDING_LENGTH = 24L

    const val DRAW_BINDING_NONE = 0
    const val DRAW_BINDING_BUFFER = 1
    const val DRAW_BINDING_TEXTURE = 2
    const val DRAW_BINDING_SAMPLER = 3

    /** How many bindings and vertex buffer slots a [DRAW_CALL] holds, from `blaze.rs`. */
    const val MAX_DRAW_BINDINGS = 32
    const val MAX_VERTEX_BUFFERS = 8

    /** `IndexFormat`: 0 = none, 1 = uint16, 2 = uint32. */
    const val INDEX_FORMAT_NONE = 0
    const val INDEX_FORMAT_UINT16 = 1
    const val INDEX_FORMAT_UINT32 = 2

    // ------------------------------------------------------------------
    // Field offsets.
    //
    // Written out rather than derived from the MemoryLayout: the ABI addresses struct fields by
    // byte offset, and naming them keeps a layout edit and its offset from drifting apart.
    // ------------------------------------------------------------------

    const val FIELD_TEXTURE_VIEW = 0L
    const val FIELD_CLEAR_VALUE = 8L

    const val BIND_GROUP_ENTRY_TYPE = 0L
    const val BIND_GROUP_ENTRY_NAME = 8L
    const val BIND_GROUP_ENTRY_FORMAT = 16L

    const val VERTEX_FORMAT_ELEMENT_OFFSET = 0L
    const val VERTEX_FORMAT_ELEMENT_FORMAT = 8L
    const val VERTEX_FORMAT_ELEMENT_NAME = 16L

    const val VERTEX_FORMAT_ELEMENTS = 0L
    const val VERTEX_FORMAT_VERTEX_SIZE = 8L

    const val DEPTH_STENCIL_COMPARE = 0L
    const val DEPTH_STENCIL_ACTIVE = 8L
    const val DEPTH_STENCIL_BIAS_CONSTANT = 16L
    const val DEPTH_STENCIL_BIAS_SLOPE_SCALE = 20L

    const val PIPELINE_NAME = 0L
    const val PIPELINE_BIND_GROUP_LAYOUTS = 8L
    const val PIPELINE_COLOR_TARGETS = 16L
    const val PIPELINE_DEPTH_STENCIL = 24L
    const val PIPELINE_VERTEX_FORMATS = 32L
    const val PIPELINE_VERTEX_SHADER = 40L
    const val PIPELINE_FRAGMENT_SHADER = 48L
    const val PIPELINE_DIRECTIVES = 56L
    const val PIPELINE_FRAG_STATE = 64L
    const val PIPELINE_TOPOLOGY = 72L

    /** `RenderPipeline#isCull`: non-zero culls back faces, which is what OpenGL did by default. */
    const val PIPELINE_CULL = 80L

    /** Byte offset of element [index] in a packed array of [layout]. */
    @JvmStatic
    fun elementOffset(layout: MemoryLayout, index: Int): Long = index * layout.byteSize()

    /** Writes `RawArray_X { contents, size }` at [base]. */
    @JvmStatic
    fun writeRawArray(target: MemorySegment, base: Long, contents: MemorySegment, size: Long) {
        target.set(PTR, base, contents)
        target.set(LONG, base + 8L, size)
    }

    // ------------------------------------------------------------------
    // GpuFormat enum (uint64_t)
    // ------------------------------------------------------------------

    const val NONE = 0L
    const val R8_UNORM = 1L
    const val R8_SNORM = 2L
    const val RG8_UNORM = 3L
    const val RG8_SNORM = 4L
    const val RGB8_UNORM = 5L
    const val RGB8_SNORM = 6L
    const val RGBA8_UNORM = 7L
    const val RGBA8_SNORM = 8L
    const val R16_UNORM = 9L
    const val R16_SNORM = 10L
    const val RG16_UNORM = 11L
    const val RG16_SNORM = 12L
    const val RGB16_UNORM = 13L
    const val RGB16_SNORM = 14L
    const val RGBA16_UNORM = 15L
    const val RGBA16_SNORM = 16L
    const val R8_UINT = 17L
    const val R8_SINT = 18L
    const val RG8_UINT = 19L
    const val RG8_SINT = 20L
    const val RGB8_UINT = 21L
    const val RGB8_SINT = 22L
    const val RGBA8_UINT = 23L
    const val RGBA8_SINT = 24L
    const val R16_UINT = 25L
    const val R16_SINT = 26L
    const val RG16_UINT = 27L
    const val RG16_SINT = 28L
    const val RGB16_UINT = 29L
    const val RGB16_SINT = 30L
    const val RGBA16_UINT = 31L
    const val RGBA16_SINT = 32L
    const val R32_UINT = 33L
    const val R32_SINT = 34L
    const val RG32_UINT = 35L
    const val RG32_SINT = 36L
    const val RGB32_UINT = 37L
    const val RGB32_SINT = 38L
    const val RGBA32_UINT = 39L
    const val RGBA32_SINT = 40L
    const val R16_FLOAT = 41L
    const val RG16_FLOAT = 42L
    const val RGB16_FLOAT = 43L
    const val RGBA16_FLOAT = 44L
    const val R32_FLOAT = 45L
    const val RG32_FLOAT = 46L
    const val RGB32_FLOAT = 47L
    const val RGBA32_FLOAT = 48L
    const val RGB10A2_UNORM = 49L
    const val RGB10A2_UINT = 50L
    const val RG11B10_FLOAT = 51L
    const val D32_FLOAT = 52L
    const val D32_FLOAT_S8_UINT = 53L
    const val D24_UNORM_S8_UINT = 54L
    const val D16_UNORM = 55L
    const val S8_UINT = 56L

    // Binding-builder entry kinds and primitive topology (bindings.h)
    const val ENTRY_TEXEL_BUFFER = 0L
    const val ENTRY_UNIFORM_BUFFER = 1L
    const val ENTRY_SAMPLER = 2L

    const val TOPOLOGY_LINES = 1L
    const val TOPOLOGY_DEBUG_LINE_STRIP = 2L
    const val TOPOLOGY_POINTS = 3L
    const val TOPOLOGY_TRIANGLES = 4L
    const val TOPOLOGY_TRIANGLE_STRIP = 5L
    const val TOPOLOGY_TRIANGLE_FAN = 6L
    const val TOPOLOGY_QUADS = 7L

    // ------------------------------------------------------------------
    // Functions, in bindings.h order
    // ------------------------------------------------------------------

    /**
     * The plan's bindings, in slot order, which is the order [DRAW_CALL]'s binding array is indexed
     * by.
     *
     * Called once per compiled pipeline; the JVM turns it into a name-to-slot table and from then on
     * nothing on the draw path hashes or compares a name. Returns 0 if the table offered was too
     * small, which the caller treats as "this pipeline cannot be drawn with".
     */
    @JvmField val pipelineBindings: MethodHandle =
        handle("pipeline_bindings", FunctionDescriptor.of(INT, PTR, PTR))

    /**
     * Records one draw: the pipeline, its buffers, every binding and the draw parameters, in one
     * call.
     *
     * This is what the per-binding entry points used to be: `bind_buffer`, `bind_texture_and_sampler`,
     * `bind_render_pipeline_to_pass`, `set_vertex_buffer`, `set_index_buffer` and the two draw
     * calls, each with a name resolved against the plan on the native side.
     */
    @JvmField val drawCall: MethodHandle =
        handle("draw_call", FunctionDescriptor.ofVoid(PTR, PTR, PTR))

    @JvmField val createCommandEncoder: MethodHandle =
        handle("create_command_encoder", FunctionDescriptor.of(PTR, PTR))

    @JvmField val clearColorTexture: MethodHandle =
        handle("clear_color_texture", FunctionDescriptor.ofVoid(PTR, PTR, INT))

    @JvmField val clearDepthTexture: MethodHandle =
        handle("clear_depth_texture", FunctionDescriptor.ofVoid(PTR, PTR, DOUBLE))

    @JvmField val clearColorAndDepthTextures: MethodHandle =
        handle("clear_color_and_depth_textures", FunctionDescriptor.ofVoid(PTR, PTR, INT, PTR, DOUBLE))

    @JvmField val clearColorAndDepthTexturesRegion: MethodHandle =
        handle(
            "clear_color_and_depth_textures_region",
            FunctionDescriptor.ofVoid(PTR, PTR, INT, PTR, DOUBLE, INT, INT, INT, INT),
        )

    /**
     * Diagnostics: writes a texture out as raw RGBA so the renderer's output can be inspected.
     *
     * The boolean flips the rows on the way out, which a render target needs - see
     * [dev.birb.wgpu.backend.Diagnostics.dumpTexture].
     */
    @JvmField val dumpTextureRgba: MethodHandle =
        handle(
            "dump_texture_rgba",
            FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, PTR, PTR, PTR, ValueLayout.JAVA_BOOLEAN),
        )

    /** The same, for the swapchain image, of which the JVM side only has the `SurfaceTexture`. */
    @JvmField val dumpSurfaceTextureRgba: MethodHandle =
        handle(
            "dump_surface_texture_rgba",
            FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, PTR, PTR, PTR),
        )

    /** Diagnostics: logs how many render passes, pipeline binds and draws happened since last call. */
    @JvmField val logRenderStats: MethodHandle = handle("log_render_stats", FunctionDescriptor.ofVoid())

    @JvmField val createTextureView: MethodHandle =
        handle("create_texture_view", FunctionDescriptor.of(PTR, PTR, PTR, INT, INT, INT))

    @JvmField val dropTextureView: MethodHandle =
        handle("drop_texture_view", FunctionDescriptor.ofVoid(PTR))

    @JvmField val createRenderPass: MethodHandle =
        handle("create_render_pass", FunctionDescriptor.of(PTR, PTR, PTR, PTR))

    @JvmField val dropRenderPass: MethodHandle =
        handle("drop_render_pass", FunctionDescriptor.ofVoid(PTR))

    /**
     * Restricts drawing in [createRenderPass]'s pass to a rectangle of its colour target.
     *
     * Coordinates are OpenGL's - measured from the target's origin row - which is the convention
     * this backend renders in, so they are forwarded as they arrive.
     */
    @JvmField val setScissorRect: MethodHandle =
        handle("set_scissor_rect", FunctionDescriptor.ofVoid(PTR, INT, INT, INT, INT))

    @JvmField val createBuffer: MethodHandle =
        handle("create_buffer", FunctionDescriptor.of(PTR, PTR, PTR, INT, LONG))

    @JvmField val createBufferInit: MethodHandle =
        handle("create_buffer_init", FunctionDescriptor.of(PTR, PTR, PTR, INT, PTR, LONG))

    @JvmField val dropBuffer: MethodHandle =
        handle("drop_buffer", FunctionDescriptor.ofVoid(PTR))

    @JvmField val allocateGpuBufferMapped: MethodHandle =
        handle("allocate_gpu_buffer_mapped", FunctionDescriptor.of(PTR, PTR, LONG, LONG))

    /**
     * The wgpu usage flags a buffer was created with, as raw bits.
     *
     * Blaze3D's usage mask is not the mask wgpu sees - `USAGE_UNIFORM_TEXEL_BUFFER` becomes
     * `STORAGE` and a mapped buffer gains `COPY_DST` - so a log line that says which flags a buffer
     * actually carries is the only way to answer "why does this draw read nothing" from the JVM.
     */
    @JvmField val bufferUsages: MethodHandle =
        handle("buffer_usages", FunctionDescriptor.of(LONG, PTR))

    @JvmField val writeToBuffer: MethodHandle =
        handle("write_to_buffer", FunctionDescriptor.ofVoid(PTR, PTR, LONG, LONG, PTR))

    /**
     * Copies a buffer range back to CPU memory, blocking until the GPU has produced it.
     *
     * The read half of `CommandEncoderBackend#mapBuffer`: wgpu has no CPU-visible mapping, so the
     * readback is mapped asynchronously and waited for while the JVM side's staging buffer is
     * filled.
     */
    @JvmField val readBuffer: MethodHandle =
        handle("read_buffer", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, PTR, PTR, LONG, LONG, PTR))

    @JvmField val writeBufferWith: MethodHandle =
        handle("write_buffer_with", FunctionDescriptor.ofVoid(PTR, PTR, PTR, LONG))

    @JvmField val flushEncoder: MethodHandle =
        handle("flush_encoder", FunctionDescriptor.ofVoid(PTR, PTR))

    @JvmField val submitCommandEncoder: MethodHandle =
        handle("submit_command_encoder", FunctionDescriptor.ofVoid(PTR, PTR))

    @JvmField val copyBufferToBuffer: MethodHandle =
        handle("copy_buffer_to_buffer", FunctionDescriptor.ofVoid(PTR, PTR, PTR, PTR, LONG, LONG, LONG))

    @JvmField val copyBufferToTexture: MethodHandle =
        handle(
            "copy_buffer_to_texture",
            FunctionDescriptor.ofVoid(
                PTR, PTR, PTR, LONG, LONG,
                INT, INT, INT, INT,
                PTR, INT, INT, INT, INT, INT, INT
            )
        )

    @JvmField val copyTextureToBuffer: MethodHandle =
        handle(
            "copy_texture_to_buffer",
            FunctionDescriptor.ofVoid(PTR, PTR, PTR, PTR, LONG, INT, INT, INT, INT, INT)
        )

    @JvmField val copyTextureToTexture: MethodHandle =
        handle(
            "copy_texture_to_texture",
            FunctionDescriptor.ofVoid(PTR, PTR, PTR, INT, INT, INT, INT, INT, INT, INT)
        )

    @JvmField val writeToTexture: MethodHandle =
        handle(
            "write_to_texture",
            FunctionDescriptor.ofVoid(PTR, PTR, PTR, LONG, INT, INT, INT, INT, INT, INT)
        )

    @JvmField val createTexture: MethodHandle =
        handle("create_texture", FunctionDescriptor.of(PTR, PTR, LONG, INT, INT, INT, INT, INT, PTR))

    @JvmField val dropTexture: MethodHandle =
        handle("drop_texture", FunctionDescriptor.ofVoid(PTR))

    /**
     * Creates a sampler with the address modes and filters Blaze3D asked for.
     *
     * The modes travel as the numbers of `com.mojang.blaze3d.textures.AddressMode` (0 `REPEAT`,
     * 1 `CLAMP_TO_EDGE`) and `FilterMode` (0 `NEAREST`, 1 `LINEAR`), and `maxLod` is the
     * `OptionalDouble` as a plain double - negative when Blaze3D did not ask for a limit. They used
     * to be dropped entirely, which clamped every texture and is what turned rain into lines.
     */
    @JvmField val createSampler: MethodHandle =
        handle(
            "create_sampler",
            FunctionDescriptor.of(PTR, PTR, INT, INT, INT, INT, INT, DOUBLE),
        )

    @JvmField val dropSampler: MethodHandle =
        handle("drop_sampler", FunctionDescriptor.ofVoid(PTR))

    @JvmField val compileRenderPipeline: MethodHandle =
        handle("compile_render_pipeline", FunctionDescriptor.of(PTR, PTR, PTR))

    /**
     * Compiles the other depth variant of a pipeline that has already been described.
     *
     * `(renderer, pipeline, depth_state_or_null) -> pipeline`. The shader work lives behind the
     * pipeline this copies from, so all that is left here is the driver's own pipeline creation -
     * which is why the second variant of a pipeline can be left until something draws with it.
     */
    @JvmField val createPipelineVariant: MethodHandle =
        handle("create_pipeline_variant", FunctionDescriptor.of(PTR, PTR, PTR, PTR))

    /**
     * Frees one compiled pipeline variant.
     *
     * `CompiledRenderPipeline` is not `AutoCloseable`, so nothing in Blaze3D calls this; the
     * pipeline cache's own clear and a cleaner do, because each compiled pipeline holds two native
     * pipelines with their bind group layouts and a copy of the descriptor.
     *
     * Null is accepted and ignored: the two depth variants are compiled lazily, so the JVM holds a
     * slot per variant and only one of them may ever have been created.
     */
    @JvmField val dropRenderPipeline: MethodHandle =
        handle("drop_render_pipeline", FunctionDescriptor.ofVoid(PTR))

    @JvmField val maxTextureSize: MethodHandle =
        handle("max_texture_size", FunctionDescriptor.of(INT, PTR))

    @JvmField val minUniformOffsetAlignment: MethodHandle =
        handle("min_uniform_offset_alignment", FunctionDescriptor.of(INT, PTR))

    // ------------------------------------------------------------------
    // Surface
    // ------------------------------------------------------------------

    @JvmField val createSurface: MethodHandle =
        handle("create_surface", FunctionDescriptor.ofVoid(PTR, LONG, LONG))

    @JvmField val configureSurface: MethodHandle =
        handle("configure_surface", FunctionDescriptor.ofVoid(PTR, INT, INT, INT))

    @JvmField val acquireNextTexture: MethodHandle =
        handle("acquire_next_texture", FunctionDescriptor.of(PTR, PTR))

    @JvmField val blitFromTexture: MethodHandle =
        handle("blit_from_texture", FunctionDescriptor.ofVoid(PTR, PTR, PTR))

    @JvmField val presentSurface: MethodHandle =
        handle("present_surface", FunctionDescriptor.ofVoid(PTR, PTR))

    @JvmField val dropSurface: MethodHandle =
        handle("drop_surface", FunctionDescriptor.ofVoid(PTR))
}

