modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/wgpu-mc/wgpu-mc/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/wgpu-mc/wgpu-mc"
logoFile="assets/wgpu_mc/icon.png"
credits="Original Fabric mod by Birb"
authors="Birb, NeoForge port contributors"
description='''
A renderer made to replace Blaze3D, written in Rust, using wgpu for cross-platform support.
Supported backends: Vulkan, D3D12, and Metal.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
